create database customer_behavior
use  customer_behavior
SELECT * FROM customer LIMIT 5;

-- Q1 )What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;

-- Q2) Which products have the highest average customer review ratings? Identify the top 5.
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Q3) How is total revenue distributed across different customer age groups?

SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Q4) Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q5) What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Q6) Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7) Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q8) Which customers are at risk of churn based on low purchase frequency,
-- and what percentage of total customers do they represent?
 
 SELECT 
    customer_id,
    previous_purchases
FROM customer
WHERE previous_purchases <= 1;

-- Identify churn-risk customers and calculate percentage
SELECT 
    COUNT(DISTINCT customer_id) AS total_customers,

    COUNT(DISTINCT CASE 
        WHEN previous_purchases <= 1 THEN customer_id 
    END) AS churn_risk_customers,

    ROUND(
        COUNT(DISTINCT CASE 
            WHEN previous_purchases <= 1 THEN customer_id 
        END) * 100.0 / COUNT(DISTINCT customer_id),
        2
    ) AS churn_risk_percentage
FROM customer;

-- Q9)Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

-- Q 10) Which products have the highest proportion of purchases made using discounts? Identify the top 5.
SELECT 
    item_purchased,
    ROUND(
        100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

select * from customer;